Virhi\DomainBundle\Entity\Data:
    type: entity
    table: data
    gedmo:
        soft_deleteable:
          field_name: deleted
          time_aware: false
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        titre:
            type: string