Virhi\DomainBundle\Entity\Post:
    type: entity
    table: post
    gedmo:
        soft_deleteable:
          field_name: deleted
          time_aware: false
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        titre:
            type: string
        post:
            column: user_email
            type: string
            nullable: true
        sousTitre:
            type: string
            nullable: true
        description:
            type: text
            nullable: true
    manyToMany:
        tags:
            targetEntity: Tag
            joinTable:
                name: tags_entity
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id