Virhi\DomainBundle\Entity\Tag:
    type: entity
    table: tag
    gedmo:
        soft_deleteable:
          field_name: deleted
          time_aware: false
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        titre:
            type: string
        description:
            type: text
            nullable: true