virhi_domain:
    resource: "@VirhiDomainBundle/Resources/config/routing.yml"
    prefix:   /

virhi_ui_rest_api_doctrine:
    resource: "@VirhiLazyRestApiUiBundle/Resources/config/routing.yml"
    prefix:   /


virhi_rest_api_doctrine:
    resource: "@VirhiLazyRestApiBundle/Resources/config/routing.yml"
    prefix:   /


virhi_admin:
    resource: "@VirhiAdminBundle/Resources/config/routing.yml"
    prefix:   /
